### ISSUE TITLE
Door stuck at Awakening level

### ISSUE THREAD

**Issue by amyren1966** [0xABADCAFE/karlos-tkg#6]
Playing the Awakening level from this archive, after crossing the bridge and flip that switch the rightmost door to the teleporter does open. But the door to the left does not open (I am not talking about the middle double-door here, but the one left of that)
I try using the teleporter and return to the brigde again to try the door once more, but it still will not open.
Tried to replicate the movements from your youtube video but no luck.

By the way, it apears to me as a bad level design if both those doors are depending on the switch above. Then it means if you accidently fall off the bridge before flipping the swicth there is no way back.

**Comment by 0xABADCAFE** [comment]
Doors and lifts that are use-key activated require that you are basically in contact with them. This is how such doors have always worked. The knifeswitch activation radius does not vary by placement, it's a property of the switch itself. Again, this hasn't changed in the mod.

**Comment by amyren1966** [comment]
Ok. Its been a while since playing the original :)

**Comment by 0xABADCAFE** [comment]
No problem. There is a new door mechanic in level B, but so far it's the only place that uses it.
